title = "Daniel Tedman"
languageCode = "en-us"
theme = "hello-friend-ng"
paginate = 100

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"
#footerLeft = "left"
footerRight = "Using <a href='https://themes.gohugo.io/hugo-theme-hello-friend-ng/'>Hello Friend NG</a> Theme"
# Subtitle for home
homeSubtitle = "As a Professional Software Engineer, I am committed to participating in the development of a secure and accessible web."
# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false
# Enable sharing buttons, if you like
enableSharingButtons = true
# Metadata mostly used in document's head
description = "As a Professional Software Engineer, I am committed to participating in the development of a secure and accessible web."
keywords = ""
images = [""]

[[params.social]]
name = "email"
url = "mailto:dbtedman@gmail.com"

[[params.social]]
name = "github"
url = "https://github.com/dbtedman"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/dbtedman"

[taxonomies]
category = "blog"
tag = "tags"
series = "series"

[languages]

[languages.en]
title = "Daniel Tedman"
subtitle = "As a Professional Software Engineer, I am committed to participating in the development of a secure and accessible web."
keywords = ""
copyright = 'Daniel Tedman'
readOtherPosts = ""
disableKinds = "RSS"

[languages.en.params.logo]
logoText = "Daniel Tedman"
logoHomeLink = "/"

# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"
# And you can even create generic menu
[[menu.main]]
identifier = "my-work"
name = "My Work"
url = "/my-work"
